/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivedRouteImport } from './routes/archived'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as DunaRouteImport } from './routes/duna'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ThreadsThreadIdRouteImport } from './routes/threads.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivedRoute = ArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const DunaRoute = DunaRouteImport.update({
  id: '/duna',
  path: '/duna',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ThreadsThreadIdRoute = ThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/compose': typeof ComposeRoute
  '/duna': typeof DunaRoute
  '/logs': typeof LogsRoute
  '/maintenance': typeof MaintenanceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/compose': typeof ComposeRoute
  '/duna': typeof DunaRoute
  '/logs': typeof LogsRoute
  '/maintenance': typeof MaintenanceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/compose': typeof ComposeRoute
  '/duna': typeof DunaRoute
  '/logs': typeof LogsRoute
  '/maintenance': typeof MaintenanceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archived'
    | '/compose'
    | '/duna'
    | '/logs'
    | '/maintenance'
    | '/projects'
    | '/search'
    | '/projects/$projectId'
    | '/threads/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archived'
    | '/compose'
    | '/duna'
    | '/logs'
    | '/maintenance'
    | '/projects'
    | '/search'
    | '/projects/$projectId'
    | '/threads/$threadId'
  id:
    | '__root__'
    | '/'
    | '/archived'
    | '/compose'
    | '/duna'
    | '/logs'
    | '/maintenance'
    | '/projects'
    | '/search'
    | '/projects/$projectId'
    | '/threads/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivedRoute: typeof ArchivedRoute
  ComposeRoute: typeof ComposeRoute
  DunaRoute: typeof DunaRoute
  LogsRoute: typeof LogsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SearchRoute: typeof SearchRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived': {
      id: '/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof ArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duna': {
      id: '/duna'
      path: '/duna'
      fullPath: '/duna'
      preLoaderRoute: typeof DunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivedRoute: ArchivedRoute,
  ComposeRoute: ComposeRoute,
  DunaRoute: DunaRoute,
  LogsRoute: LogsRoute,
  MaintenanceRoute: MaintenanceRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SearchRoute: SearchRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
